CREATE TABLE Agenda
(
CadastroId INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
Nome VARCHAR (60) NOT NULL,
DataDeNascimento DATE NOT NULL,
Email VARCHAR(50) NOT NULL,
Prefixo INT NOT NULL,
Telefone INT NOT NULL,
DataCadastro DATE NOT NULL DEFAULT CURRENT_DATE,
PRIMARY KEY (CadastroId)
);

ALTER TABLE Agenda