/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senac.view;

import br.com.senac.servico.ListaServico;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AnaPaula
 */
public class Listar extends javax.swing.JInternalFrame {

    /**
     * Creates new form Listar
     */
    public Listar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuOpcao = new javax.swing.JPanel();
        mostrarLista = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        gridLista = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Lista de Contatos");

        menuOpcao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opção", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16))); // NOI18N

        mostrarLista.setText("Mostrar Lista");
        mostrarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarListaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuOpcaoLayout = new javax.swing.GroupLayout(menuOpcao);
        menuOpcao.setLayout(menuOpcaoLayout);
        menuOpcaoLayout.setHorizontalGroup(
            menuOpcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuOpcaoLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(mostrarLista)
                .addContainerGap(144, Short.MAX_VALUE))
        );
        menuOpcaoLayout.setVerticalGroup(
            menuOpcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuOpcaoLayout.createSequentialGroup()
                .addComponent(mostrarLista)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Todos os Contatos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        gridLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Data de Nasc", "E-mail", "Prefixo", "Telefone"
            }
        ));
        jScrollPane1.setViewportView(gridLista);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuOpcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuOpcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        setBounds(250, 10, 433, 456);
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarListaActionPerformed
        try {
            DefaultTableModel model = (DefaultTableModel) gridLista.getModel();
            model.setRowCount(0);
            ArrayList<Object[]> agenda = ListaServico.gerarLista();
            for (Object[] o : agenda) {
                model.addRow(o);
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_mostrarListaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable gridLista;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel menuOpcao;
    private javax.swing.JButton mostrarLista;
    // End of variables declaration//GEN-END:variables
}
